CMS/Controllers/ServiceController.cs
using CMS.App_Start;
using CMS.Models.DAL;
using CMS.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CMS.Controllers
{
    public class ServiceController : Controller
    {
        private CMSEntities db = new CMSEntities();

        private IRepository<Service> _serviceRepository;

        public ServiceController()
        {
            this._serviceRepository = new ServiceRepository(new CMSEntities());

        }

        const string prefix = "Serv-";

        string getString = Helpers.Helper.RandomStringGenerator(10);

        string caseYear = DateTime.Now.Year.ToString();

        public async Task<ActionResult> LodgeServiceDelivery()
        {
            var villageList = await db.Villages.ToListAsync();

            var headsmenList = await db.Headsmen.ToListAsync();

            var dwellerList = await db.Dwellers.ToListAsync();

            IEnumerable<SelectListItem> villageRecord = from s in villageList

                                                        select new SelectListItem
                                                        {
                                                            Value = s.Id.ToString(),

                                                            Text = s.Name
                                                        };

            IEnumerable<SelectListItem> headsmenRecord = from s in headsmenList

                                                         select new SelectListItem
                                                         {
                                                             Value = s.Id.ToString(),

                                                             Text = $"Headsmen: {s.Name} {s.LastName}"
                                                         };

            IEnumerable<SelectListItem> dwellerRecord = from s in dwellerList

                                                         select new SelectListItem
                                                         {
                                                             Value = s.Id.ToString(),

                                                             Text = $"Dweller: {s.Name} {s.LastName}"
                                                         };


            ViewBag.WardId = new SelectList(db.Wards, "Id", "Description");

            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Description");

            ViewBag.ServiceTypeId = new SelectList(db.ServiceTypes, "Id", "Type");

            ViewBag.ServiceStatusId = new SelectList(db.ServiceStatus, "Id", "Status");

            ViewBag.TribalAuthorityId = new SelectList(db.TribalAuthorities, "Id", "AuthorityName");

            ViewBag.DwellerId = new SelectList(dwellerRecord, "Value", "Text");

            ViewBag.VillageId = new SelectList(villageRecord, "Value","Text");

            ViewBag.HeadsmenId = new SelectList(headsmenRecord, "Value", "Text");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LodgeServiceDelivery(Service service)
        {
            string referenceNumber = prefix + getString + "-" + caseYear;

            ViewBag.referenceNum = referenceNumber;

            service.ReferenceNumber = referenceNumber;

            UploadImage(service);

            service.Id = Guid.NewGuid();

            if (ModelState.IsValid)
            {

                _serviceRepository.InsertRecordAsync(service);

                await _serviceRepository.SaveAsync();

                return RedirectToAction("RegisteredService");
            }

            ViewBag.HeadsmenId = new SelectList(db.Headsmen, "Id", "Name", service.HeadsmenId);

            ViewBag.VillageId = new SelectList(db.Villages, "Id", "Name", service.VillageId);

            ViewBag.TribalAuthorityId = new SelectList(db.TribalAuthorities, "Id", "", service.TribalAuthorityId);

            return View();
        }

        private void UploadImage(Service service)
        {

            string fileName = Path.GetFileNameWithoutExtension(service.FileBase.FileName);

            string extension = Path.GetExtension(service.FileBase.FileName);

            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;

            service.ImageFile = "~/TribalImage/" + fileName;

            fileName = Path.Combine(Server.MapPath("~/TribalImage/"), fileName);

            service.FileBase.SaveAs(fileName);
        }
        
        public async Task<ActionResult> ServiceDeliveryCollection()
        {

            var service = from n in await _serviceRepository.RetrieveAllRecordsAsync()

                          select n;

            return View(service);
        }

        public async Task<ActionResult> ModifyService(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var service = await _serviceRepository.RetrieveRecordAsync(id);

            if (service == null)
            {
                return HttpNotFound();
            }

            var headsmen = await db.Headsmen.ToListAsync();

            IEnumerable<SelectListItem> getHeadsmen = from s in headsmen

                                                      select new SelectListItem
                                                      {
                                                          Value = s.Id.ToString(),

                                                          Text = $"Headsmen: {s.Name} {s.LastName}"
                                                      };



            ViewBag.WardId = new SelectList(db.Wards, "Id", "Description");

            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Description");

            ViewBag.ServiceTypeId = new SelectList(db.ServiceTypes, "Id", "Type");

            ViewBag.ServiceStatusId = new SelectList(db.ServiceStatus, "Id", "Status");

            ViewBag.VillageId = new SelectList(db.Villages, "Id", "Name");

            ViewBag.HeadsmenId = new SelectList(getHeadsmen, "Value", "Text");

            return View(service);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ModifyService(Service service)
        {
            if (ModelState.IsValid)
            {
                _serviceRepository.UpdateRecord(service);

                await _serviceRepository.SaveAsync();

                return RedirectToAction("ServiceCollection");
            }
            var headsmen = db.Headsmen.ToList();

            IEnumerable<SelectListItem> getHeadsmen = from s in headsmen

                                                      select new SelectListItem
                                                      {
                                                          Value = s.Id.ToString(),

                                                          Text = $"Headsmen: {s.Name} {s.LastName}"
                                                      };

            ViewBag.WardId = new SelectList(db.Wards, "Id", "Description");

            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Description");

            ViewBag.ServiceTypeId = new SelectList(db.ServiceTypes, "Id", "Type");

            ViewBag.ServiceStatusId = new SelectList(db.ServiceStatus,"Id","Status");

            ViewBag.VillageId = new SelectList(db.Villages, "Id", "Name");

            ViewBag.HeadsmenId = new SelectList(getHeadsmen, "Value", "Text");

            return View();

        }
    }
}

CMS/Views/Service/LodgeServiceDelivery.cshtml
@model CMS.App_Start.Service

@{
    ViewBag.Title = "Add Service Delivery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <style>
        .note {
            text-align: center;
            height: 50px;
            background: -webkit-linear-gradient(left, #0072ff, #8811c5);
            color: #fff;
            font-weight: bold;
            line-height: 50px;
        }

        .form-content {
            padding: 5%;
            border: 1px solid #ced4da;
            margin-bottom: 2%;
        }

        .form-control {
            border-radius: 1.5rem;
        }

        .btnSubmit {
            border: none;
            border-radius: 1.5rem;
            padding: 1%;
            width: 20%;
            cursor: pointer;
            background: #0062cc;
            color: #fff;
        }
    </style>
    <link href="~/Content/bootstrap-chosen.css" rel="stylesheet" />


    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
</head>

@using (Html.BeginForm("LodgeServiceDelivery", "Service", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<body>

    <div class="note mt-3 mb-3">
        <p>Lodge Service Delivery Incident</p>
    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label id="name" for="inputRoomNum">Reference Number</label>
            @Html.EditorFor(model => model.ReferenceNumber, (String)ViewBag.referenceNum, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

        </div>

        <div class="form-group col-md-3">
            <label id="name" for="inputRoomNum">Area Name</label>
            @Html.EditorFor(model => model.AreaName, new { htmlAttributes = new { @class = "form-control", @id = "AreaName" } })
        </div>

        <div class="form-group col-md-3">
            <label id="name" for="inputRoomNum">Description</label>
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @id = "Description" } })
        </div>

        <div class="form-group col-md-3">
            <label id="name" for="inputRoomNum">Incident Photo</label>
            <input class="form-control text-box" type="file" name="FileBase" id="ImageFile" required />
        </div>


        <div class="form-group col-md-4">
            <label for="inputRoomNum">Dweller</label>
            @Html.DropDownList("DwellerId", ViewBag.DwellerId as SelectList, htmlAttributes: new { @class = "form-control", @id = "Dweller" })
        </div>



        <div class="form-group col-md-3">
            <label id="lName" for="inputRoomNum">Village</label>
            @Html.DropDownList("VillageId", ViewBag.VillageId as SelectList, htmlAttributes: new { @class = "form-control", @id = "Village" })
        </div>


        <div class="form-group col-md-3">
            <label for="inputRoomNum">Headsmen</label>
            @Html.DropDownList("HeadsmenId", ViewBag.HeadsmenId as SelectList, htmlAttributes: new { @class = "form-control", @id = "Headsmen" })

        </div>

        <div class="form-group col-md-2">
            <label for="inputRoomNum">Ward</label>
            @Html.DropDownList("WardId", ViewBag.WardId as SelectList, htmlAttributes: new { @class = "form-control", @id = "Ward" })
        </div>

        <div class="form-group col-md-3">
            <label for="inputRoomNum">Section</label>
            @Html.DropDownList("SectionId", ViewBag.SectionId as SelectList, htmlAttributes: new { @class = "form-control", @id = "Section" })

        </div>


        <div class="form-group col-md-3">
            <label for="inputRoomNum">Service Type</label>
            @Html.DropDownList("ServiceTypeId", ViewBag.ServiceTypeId as SelectList, htmlAttributes: new { @class = "form-control", @id = "ServiceType" })

        </div>

        <div class="form-group col-md-2">
            <label for="inputRoomNum">Service Status</label>
            @Html.DropDownList("ServiceStatusId", ViewBag.ServiceStatusId as SelectList, htmlAttributes: new { @class = "form-control", @id = "ServiceStatus" })
        </div>

        <div class="form-group col-md-2">
            <label for="inputRoomNum">Tribal Authority </label>
            @Html.DropDownList("TribalAuthorityId", ViewBag.TribalAuthorityId as SelectList, htmlAttributes: new { @class = "form-control", @id = "TribalAuthority" })
        </div>
    </div>
        
        <br />
        <div>
            <button type="submit" id="btnSubmit" value="Create" onclick="return validateData()" class="btn btn-outline-success pull-right"><i class="fa fa-save"></i> Save Case</button>
            <button type="button" id="btnReset" class="btn btn-outline-warning pull-right"><i class="fa fa-redo"></i> Reset</button>
            <button type="button" id="btnClose" class="btn btn-outline-danger float-right"><i class="fa fa-window-close"></i> Close</button>
        </div>
        
</body>

}


</html>

CMS/Views/Service/ModifyService.cshtml
@model CMS.App_Start.Service

<link href="~/Content/StyleForm.css" rel="stylesheet" />
<link href="~/Content/bootstrap-chosen.css" rel="stylesheet" />


@Scripts.Render("~/bundles/modernizr")

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

<style>
    #HeadsmenId, #VillageId, #inputName, #inputSurname,
    #inputGender, #inputRace, #inputIdNum, #inputCell, #inputMail, #postalRes, #postalPostal,
    #EducationId, #WorkTypeId, #IncomeSourceId {
        border-color: #000000;
    }
</style>

@using (Html.BeginForm("ModifyService", "Service", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <button type="button" class="btn btn-success float-right"><i class="fa fa-home"></i> Register Service</button>

    <div class="note mt-3 mb-3">
        <p>Service Information</p>
    </div>

            <div class="col-xl-12 col-md-12">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="container register-form">
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label for="inputRoomNum">Reference Number</label>
                                @Html.EditorFor(model => model.ReferenceNumber, new { htmlAttributes = new { @class = "form-control", @id = "inputOcc", @required = "required", placeholder = @Html.DisplayNameFor(m => m.ReferenceNumber) } })
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputAreaName">Area Name</label>
                                @Html.EditorFor(model => model.AreaName, new { htmlAttributes = new { @class = "form-control", @id = "inputOcc", @required = "required", placeholder = @Html.DisplayNameFor(m => m.AreaName) } })
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputAreaName">Description</label>
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @id = "inputOcc", @required = "required", placeholder = @Html.DisplayNameFor(m => m.Description) } })
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputIncome">Service Type</label>
                                @Html.DropDownList("ServiceTypeId", ViewBag.ServiceTypeId as SelectList, htmlAttributes: new { @class = "form-control", @id = "ServiceType" })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputRoomNum">Village</label>
                                @Html.DropDownList("VillageId", null, htmlAttributes: new { @class = "form-control chosen-select", @id = "Village" })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputRoomNum">Ward</label>
                                @Html.DropDownList("WardId", null, htmlAttributes: new { @class = "form-control chosen-select", @id = "Ward" })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputRoomNum">Ward</label>
                                @Html.DropDownList("SectionId", null, htmlAttributes: new { @class = "form-control chosen-select", @id = "Section" })
                            </div>

                            <div class="form-group col-md-4">
                                <label for=" ServiceStatus">Service Status</label>
                                @Html.DropDownList("ServiceStatusId", null, htmlAttributes: new { @class = "form-control chosen-select", @id = "ServiceStatus" })
                            </div>

                            <div class="form-group col-md-6">
                                <label for="inputEducation">Headsmen</label>
                                @Html.DropDownList("HeadsmenId", null, htmlAttributes: new { @class = "form-control chosen-select", @id = "Headsmen" })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputProvince">Incident Image</label>
                                <input class="form-control text-box" type="file" name="FileBase" id="ImageFile" required />
                            </div>
                        </div>
                        


                        <div style="background-color:whitesmoke" class="mt-3 pull-right">
                            <button type="submit" id="btnSubmit" value="Create" onclick="return validateData()" class="btn btn-outline-success pull-right"><i class="fa fa-user-plus"></i> Update Services </button>
                            @Html.ActionLink(" Add ServiceFeedback", "GetServiceFeedback", "ServiceFeedback", new { @ServiceId = Model.Id }, new { @class = "btn btn-outline-secondary float-right fa fa-user" })
                            @Html.ActionLink(" View ServiceFeedback", "RegisteredServiceFeedback", "ServiceFeedback", new { @ServiceFeedbackId = Model.Id }, new { @class = "btn btn-outline-warning mr-1 float-right fa fa-eye" })
                        </div>
                    </div>
                    <br />
                </div>
            </div>
}

CMS/Views/Service/ServiceDeliveryCollection.cshtml
@model IEnumerable<CMS.App_Start.Service>
@using GridMvc.Html

@{
    ViewBag.Title = "Index";


}

<p class="row">
    <li class="btn btn-outline-secondary ml-2"><a href="@Url.Action("LodgeServiceDelivery", "Service")"><i class="fas fa-plus"></i> Lodge Service Incident</a></li>
    <li class="btn btn-outline-danger mr-2 float-right"><a href="@Url.Action("ServiceDelivery", "Service")"><i class="fa fa-window-close"></i> Close</a></li>

</p>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">List of All Service</h6>
    </div>
    <div class="card-body">
        <div class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <table class="table thead-dark table-striped" id="DwellerTbl">
                <thead>
                    <tr>
                        <th>
                            Reference Number
                        </th>
                        <th>
                            Area Name
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Dweller
                        </th>
                       
                        <th>Action</th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReferenceNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AreaName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Dweller.Name)
                        </td>
                        
                        <td class="btn-group">
                            <li class="btn btn-outline-success "><a href="@Url.Action("ModifyService", "Service", new { id = item.Id})"><i class="fa fa-edit"></i> Modify</a></li>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

@section scripts{

    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="cdn.datatables.net/1.11.1/css/jquery.dataTables.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.4.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

    <script>

        $(function () {

            $(document).ready(function () {
                $('#DwellerTbl').DataTable();
            });

        });

    </script>
}