CMS/Controllers/PlotController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CMS.App_Start;
using CMS.Models;
using CMS.Models.DAL;
using CMS.Models.Repositories;



namespace CMS.Controllers
{
    public class PlotController : Controller
    {
        private CMSEntities db = new CMSEntities();

        private IRepository<PlotTbl> _plotRepository;

        public PlotController()
        {
            _plotRepository = new PlotRepository(new CMSEntities());
        }
        public async Task<ActionResult> Index()
        {
            var plot = from n in await _plotRepository.RetrieveAllRecordsAsync()
                           select n;
            return View(plot);
        }

       
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
          
            var plot = await _plotRepository.RetrieveRecordAsync(id);

            if (plot == null)
            {
                return HttpNotFound();
            }
            return View(plot);
        }

        public async Task<ActionResult> PlotRegistration()
        {
            var condition = await db.Conditions.ToListAsync();
            var country = await db.Countries.ToListAsync();
            var municipality = await db.Municipalities.ToListAsync();
            var province = await db.Provinces.ToListAsync();
            var section = await db.Sections.ToListAsync();
            var ward = await db.Wards.ToListAsync();
            var village = await db.Villages.ToListAsync();



            var enumData = from eRentalCycle e in Enum.GetValues(typeof(eRentalCycle))
                           select new
                           {
                               ID = (int)e,
                               Name = e.ToString()
                           };


            IEnumerable<SelectListItem> getConditions = from s in condition
                                                      select new SelectListItem
                                                      {
                                                          Value = s.Id.ToString(),
                                                          Text = s.Condition1
                                                      };

            IEnumerable<SelectListItem> getMunicipality = from s in municipality
                                                        select new SelectListItem
                                                        {
                                                            Value = s.Id.ToString(),
                                                            Text = s.Name
                                                        };

            IEnumerable<SelectListItem> sectionList = from s in section
                                                        select new SelectListItem
                                                        {
                                                            Value = s.Id.ToString(),
                                                            Text = s.Description
                                                        };


            ViewBag.EnumList = new SelectList(enumData, "ID", "Name");
            ViewBag.ConditionId = getConditions;
            ViewBag.CountryId = new SelectList(_plotRepository.OnGetCountry(), "Id", "Country1");
            ViewBag.MunicipalityId = getMunicipality;
            ViewBag.ProvinceId = new SelectList(_plotRepository.OnGetProvince(), "Id", "Province1");
            ViewBag.SectionId = sectionList;
            ViewBag.VillageId = new SelectList(db.Villages, "Id", "Name");
            ViewBag.WardId = new SelectList(db.Wards, "Id", "Description");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PlotRegistration(PlotTbl plotTbl)
        {
            plotTbl.LeaseCycle = (int)eRentalCycle.Annually;

            plotTbl.PlotNumber = $"Pl/{Helpers.Helper.RandomStringGenerator(5)}/{DateTime.Now.Year}";

            if (ModelState.IsValid)
            {
                plotTbl.Id = Guid.NewGuid();

                plotTbl.IsActive = true;

                _plotRepository.InsertRecordAsync(plotTbl);

                await _plotRepository.SaveAsync();

                return RedirectToAction("Index");
            }

            ViewBag.ConditionId = new SelectList(db.Conditions, "Id", "Condition1", plotTbl.ConditionId);
            ViewBag.CountryId = new SelectList(db.Countries, "Id", "Country1", plotTbl.CountryId);
            ViewBag.MunicipalityId = new SelectList(db.Municipalities, "Id", "Name", plotTbl.MunicipalityId);
            ViewBag.ProvinceId = new SelectList(db.Provinces, "Id", "Province1", plotTbl.ProvinceId);
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Description", plotTbl.SectionId);
            ViewBag.VillageId = new SelectList(db.Villages, "Id", "Name", plotTbl.VillageId);
            ViewBag.WardId = new SelectList(db.Wards, "Id", "Description", plotTbl.WardId);

            return View(plotTbl);
        }

        public async Task<ActionResult> ModifyPlot(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            var plot = await _plotRepository.RetrieveRecordAsync(id);

            if (plot == null)
            {
                return HttpNotFound();
            }

            var enumData = from eRentalCycle e in Enum.GetValues(typeof(eRentalCycle))
                           select new
                           {
                               ID = (int)e,
                               Name = e.ToString()
                           };

            ViewBag.EnumList = new SelectList(enumData, "ID", "Name");
            ViewBag.ConditionId = new SelectList(db.Conditions, "Id", "Condition1", plot.ConditionId);
            ViewBag.CountryId = new SelectList(db.Countries, "Id", "Country1", plot.CountryId);
            ViewBag.MunicipalityId = new SelectList(db.Municipalities, "Id", "Name", plot.MunicipalityId);
            ViewBag.ProvinceId = new SelectList(db.Provinces, "Id", "Province1", plot.ProvinceId);
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Description", plot.SectionId);
            ViewBag.VillageId = new SelectList(db.Villages, "Id", "Name", plot.VillageId);
            ViewBag.WardId = new SelectList(db.Wards, "Id", "Description", plot.WardId);

            return View(plot);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ModifyPlot(PlotTbl plot)
        {
            if (ModelState.IsValid)
            {
                _plotRepository.UpdateRecord(plot);
                await _plotRepository.SaveAsync();

                return RedirectToAction("Index");
            }

            ViewBag.ConditionId = new SelectList(db.Conditions, "Id", "Condition1", plot.ConditionId);
            ViewBag.CountryId = new SelectList(db.Countries, "Id", "Country1", plot.CountryId);
            ViewBag.MunicipalityId = new SelectList(db.Municipalities, "Id", "Name", plot.MunicipalityId);
            ViewBag.ProvinceId = new SelectList(db.Provinces, "Id", "Province1", plot.ProvinceId);
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Description", plot.SectionId);
            ViewBag.VillageId = new SelectList(db.Villages, "Id", "Name", plot.VillageId);
            ViewBag.WardId = new SelectList(db.Wards, "Id", "Description", plot.WardId);

            return View(plot);
        }


        public async Task<ActionResult> BuyPlot(Guid plotId)
        {
            var plot = await _plotRepository.RetrieveRecordAsync(plotId);

            if (plot != null)
            {
                ViewData["plotRecord"] = plot;
                ViewData["plotNum"] = plot.PlotNumber;
                ViewData["Amount"] = $"R {plot.AmountPaid}";
                ViewData["Size"] = plot.Hectare;
                ViewData["Muni"] = plot.Municipality.Name;
            }

            return View();
        }

       
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlotTbl plot = db.PlotTbls.Find(id);
            if (plot == null)
            {
                return HttpNotFound();
            }
            return View(plot);
        }

      
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PlotTbl plot = db.PlotTbls.Find(id);
            db.PlotTbls.Remove(plot);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //[HttpGet]
        //public ActionResult RentalCycle()
        //{
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult RentalCycle(PlotTbl model)
        //{

        //    model.Id = Helpers.Helper.GenerateGuid();



        //    if (ModelState.IsValid)
        //    {
        //        db.PlotTbls.Add(model);

        //        db.SaveChanges();

        //        return RedirectToAction("PropertyRegistration");

        //    }
        //    else
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        public enum eRentalCycle
         {

CMS/Views/Plot/BuyPlot.cshtml
<link href="~/Content/StyleForm.css" rel="stylesheet" />
@{
    ViewBag.Title = "BuyPlot";
}

@if (ViewData["plotRecord"] == null)
{
    <div class="alert alert-dark" role="alert">
        Unfortunately we ran into a problem!
        Our Technicians have been alerted about it however.

        <a class="btn btn-outline-danger" @Html.Action("Index", "Plot")><i class="fa fa-undo"></i> Back</a>
    </div>
}
else
{
    <button type="button" class="btn btn-success float-right"><i class="fa fa-home"></i> Existing Plots</button>

    <div class="note mt-3 mb-3">
        <p>Plot Purchasing</p>
    </div>

    <div class="col-xl-12 col-md-12">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="container register-form">

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="PropType">Plot Number</label>
                        @Html.TextBox("Number", ViewData["plotNum"], new { @class = "form-control", @readonly = "readonly" })

                    </div>

                    <div class="form-group col-md-6">
                        <label for="PropType">Amount</label>
                        @Html.TextBox("Amount", ViewData["Amount"], new { @class = "form-control", @readonly = "readonly" })
                    </div>

                    <div class="form-group col-md-6">
                        <label for="PropType">Plot Size</label>
                        @Html.TextBox("Size", ViewData["Size"], new { @class = "form-control", @readonly = "readonly" })
                    </div>


                    <div class="form-group col-md-6">
                        <label for="PropType">Municipality</label>
                        @Html.TextBox("Muni", ViewData["Muni"], new { @class = "form-control", @readonly = "readonly" })
                    </div>

                </div>

                <div class="btn-group" style="background-color:whitesmoke">
                    <a class="btn btn-outline-success"><i class="fa fa-file-invoice"></i> Buy Plot</a>
                    <a class="btn btn-outline-danger"><i class="fa fa-file-pdf"></i> Print Invoice</a>
                </div>

            </div>
        </div>
    </div>
}

CMS/Views/Plot/Delete.cshtml
@model CMS.App_Start.PlotTbl

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Plot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlotNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlotNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hectare)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hectare)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsLeased)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsLeased)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeasePeriodId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeasePeriodId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GPSCoordinate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GPSCoordinate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Condition.Condition1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Condition.Condition1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.Country1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Country1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Province.Province1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Province.Province1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CMS/Views/Plot/Index.cshtml
@model IEnumerable<CMS.App_Start.PlotTbl>
@using GridMvc.Html

@{
    ViewBag.Title = "Index";


}

<p class="row">
    <li class="btn btn-outline-secondary ml-2"><a href="@Url.Action("PlotRegistration", "Plot")"><i class="fas fa-plus"></i> Add New Plot</a></li>
    <li class="btn btn-outline-danger mr-2 float-right"><a href="@Url.Action("RegisterDweller", "Dweller")"><i class="fa fa-window-close"></i> Close</a></li>

</p>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">List of All Registered Plots</h6>
    </div>
    <div class="card-body">
        <div class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <table class="table thead-dark" id="PlotTbl">
                <thead>
                    <tr>
                        <th>
                            Plot Number
                        </th>
                        <th>
                            Amount
                        </th>
                        <th>
                           Hectare
                        </th>
                        <th>
                            Country
                        </th>
                        <th>
                            Province
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlotNumber)
                        </td>
                        <td>
                           R @Html.DisplayFor(modelItem => item.AmountPaid)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Hectare)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country.Country1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Province.Province1)
                        </td>
                        <td class="btn-group">
                            <li class="btn btn-outline-success "><a href="@Url.Action("ModifyPlot", "Plot", new { id = item.Id})"><i class="fa fa-edit"></i> Modify</a></li>
                            <li class="btn btn-outline-dark "><a href="@Url.Action("BuyPlot", "Plot", new { plotId = item.Id})"><i class="fa fa-shopping-cart"></i> Buy</a></li>

                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

@section scripts{

    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="cdn.datatables.net/1.11.1/css/jquery.dataTables.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.4.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

    <script>

        $(function () {

            $(document).ready(function () {
                $('#PlotTbl').DataTable();
            });

        });

    </script>
}

CMS/Views/Plot/ModifyPlot.cshtml
@model CMS.App_Start.PlotTbl

<style>
    .note {
        text-align: center;
        height: 50px;
        background: -webkit-linear-gradient(left, #0072ff, #8811c5);
        color: #fff;
        font-weight: bold;
        line-height: 50px;
    }

    .form-content {
        padding: 5%;
        border: 1px solid #ced4da;
        margin-bottom: 2%;
    }

    .form-control {
        border-radius: 1.5rem;
    }

    .btnSubmit {
        border: none;
        border-radius: 1.5rem;
        padding: 1%;
        width: 20%;
        cursor: pointer;
        background: #0062cc;
        color: #fff;
    }

    .chosen-container {
        width: 95% !important;
    }

    .chosen-container-single .chosen-single {
        height: 50px;
        border-radius: 30px;
        border: 1px solid #CCCCCC;
    }
</style>
<link href="~/Content/bootstrap-chosen.css" rel="stylesheet" />


@Scripts.Render("~/bundles/modernizr")

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

@using (Html.BeginForm("ModifyPlot", "Plot", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active " id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Plot Registration</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Address Config</a>
            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Accounts & Payment</a>

        </div>

    </nav>
    <button type="button" class="btn btn-success float-right"><i class="fa fa-home"></i> Existing Plots</button>

    <div class="note mt-3 mb-3">
        <p>Modify Plot Details</p>
    </div>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            <div class="col-xl-12 col-md-12">
                <div class="card border-left-primary shadow h-100 py-2">
                    @Html.HiddenFor(model => model.Id)
                    <div class="container register-form">

                        <div class="form-group" style="background-color:antiquewhite">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsLeased, new { htmlAttributes = new { @id = "chkIsLeased" } })
                            </div>
                            <label>Is Leased?</label>
                        </div>

                        <div class="form-row">

                            <div class="form-group col-md-6">
                                <label for="PropType">Plot Number (Auto Generated)</label>
                                @Html.EditorFor(model => model.PlotNumber, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="HouseNum">Lease Period (Eg 3 months)</label>
                                @Html.EditorFor(model => model.LeasePeriod, new { htmlAttributes = new { @class = "form-control", @id = "leasePeriod" } })
                            </div>

                            <div class="form-group col-md-4">
                                <label for="inputRent">Lease Start Date</label>
                                @Html.EditorFor(model => model.LeaseStartDate, new { htmlAttributes = new { @class = "form-control", @id = "leaseStartPeriod" } })
                            </div>


                            <div class="form-group col-md-4">
                                <label for="AmountPaid">Lease End Date</label>
                                @Html.EditorFor(model => model.LeaseEndDate, new { htmlAttributes = new { @class = "form-control", @id = "leaseEndPeriod" } })
                            </div>

                            <div class="form-group col-md-4">
                                <label for="PropCondition">Plot Condition</label>
                                @Html.DropDownList("ConditionId", null, htmlAttributes: new { @class = "form-control" })
                            </div>

                            @*<div class="form-group col-md-4">
                                    <label for="inputStandNo">Lease Cycle</label>
                                    @Html.DropDownList("EnumList", ViewBag.EnumList as SelectList, htmlAttributes: new { @class = "form-control",@id="leaseCycle" })
                                </div>*@
                            <div class="form-group col-md-4">
                                <label for="PropStatus">Plot Size(Squared Metres)</label>
                                @Html.EditorFor(model => model.Hectare, new { htmlAttributes = new { @class = "form-control", @id = "plotSize" } })

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            <div class="col-xl-12 col-md-12">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="container register-form">
                        <div class="form-row">


                            <div class="form-group col-md-4">
                                <label for="inputName">Country</label>
                                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control", @id = "ProvinceId" })
                            </div>

                            <div class="form-group col-md-4">
                                <label for="inputName">Province</label>
                                @Html.DropDownList("ProvinceId", null, htmlAttributes: new { @class = "form-control", @id = "ProvinceId" })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputLastName">Municipality</label>
                                @Html.DropDownList("MunicipalityId", null, htmlAttributes: new { @class = "form-control", @id = "municipalityId" })
                            </div>

                            <div class="form-group col-md-4">
                                <label for="VillType">Applicable Village</label>
                                @Html.DropDownList("VillageId", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputCell">Section (If Applicable)</label>
                                @Html.DropDownList("SectionId", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputRoomNum">Ward</label>
                                @Html.DropDownList("WardId", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
            <div class="col-xl-12 col-md-12">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="container register-form">
                        <div class="row">
                            <div class="form-group col-md-4">
                                <label for="inputRoomNum">Lease Amount</label>
                                @Html.EditorFor(model => model.LeaseAmount, new { htmlAttributes = new { @class = "form-control", @id = "leaseAmount" } })
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputRoomNum">Amount Paid (If Cash)</label>
                                @Html.EditorFor(model => model.AmountPaid, new { htmlAttributes = new { @class = "form-control", @id = "amountPaid" } })
                            </div>
                            <br />
                        </div>

                        <div class="form-group col-md-4">
                            @Html.EditorFor(model => model.IsActive)
                            <label for="inputIsActive">Is Active?</label>
                        </div>
                        <div style="background-color:whitesmoke" class="mt-3 pull-right">
                            <button type="submit" id="btnSubmit" value="Create" onclick="return validateData()" class="btn btn-outline-success pull-right"><i class="fa fa-church"></i> Register Plot</button>
                            <button type="button" id="btnReset" class="btn btn-outline-warning pull-right"><i class="fa fa-redo"></i> Reset</button>
                            <button type="button" class="btn btn-outline-primary float-right ml-2"><i class="fa fa-eye"></i> View Plots</button>
                            <button type="button" class="btn btn-outline-danger float-right"><i class="fa fa-file-pdf"></i> Proof of Purchase</button>
                        </div>
                    </div>
                    <br />
                </div>
            </div>
        </div>
    </div>

    @section scripts{
        <script>

            $(function () {

                $("#dwellerId").chosen();
                $("#municipalityId").chosen();

                $("#chkIsLeased").change(function () {

                    if ($(this).is(":checked")) {

                        $("#amountPaid").attr("disabled", true);

                        $("#leasePeriod").attr("disabled", false);
                        $("#leaseStartPeriod").attr("disabled", false);
                        $("#leaseEndPeriod").attr("disabled", false);
                        $("#leaseCycle").attr("disabled", false);
                        $("#leaseAmount").attr("disabled", false);

                    } else {

                        $("#amountPaid").attr("disabled", false);
                        $("#leasePeriod").attr("disabled", true);
                        $("#leaseStartPeriod").attr("disabled", true);
                        $("#leaseEndPeriod").attr("disabled", true);
                        $("#leaseCycle").attr("disabled", true);
                        $("#leaseAmount").attr("disabled", true);

                    }

                });

                $("#btnSubmit").click(function () {

                    if ($("#plotSize").val() == "") {
                        swal("Plot Registration", "Error: Plot Size Required!", "error");
                        return false;
                    }

                    else {
                        swal("Plot Registration", "Plot Registered Successfully Should you have any beneficiaries, they can also be added.", "success");
                        return true;
                    }

                });
            });

        </script>
    }
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
}